### PR TITLE
added .gitattributes with export-ignore tests, docs

### PR DESCRIPTION
**Pull request by iamvar**
added .gitattributes with export-ignore tests, docs...

### CODE REVIEW

**Comment by iamvar** [comment]
My changes do not affect any requirements.
It looks like something is broken by another commit

**Comment by TomasVotruba** [comment]
I see. Could you look at it and fix those too?

**Comment by iamvar** [comment]
added dependencies in github actions

**Comment by iamvar** [comment]
Can you please merge?

**Comment by TomasVotruba** [comment]
I missed the CI fix commit in notifications. Sure :+1: 

Thank you

**Pull request merged**
