### PR TITLE
Refactoring tests to dependency injection container based + use interfaces over traits for detection

### PR DESCRIPTION
**Pull request by TomasVotruba**
- Closes #237 - **Sluggable** as interface
- Closes #325 - **Geocodable** as interface
- Closes #322 - **Translatable** as interface
- Closes #242 - **Timestampable** as interface
- Closes #324 - **Loggable** as interface
- Closes #248 - **SoftDeletable** as interface
- Closes #249 - **Sortable** as interface
- Closes #246 - **Tree** as interface

---

- Closes #421

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Looks like I lost all my credits for those PRs :)

**Comment by TomasVotruba** [comment]
There you go
https://github.com/KnpLabs/DoctrineBehaviors/pull/442#issue-351497710

**Comment by bocharsky-bw** [comment]
I mean PRs were just closed and files re-created from scratch on behalf of you, so no my commits were leaked into the repo :)

Anyway, thanks for integrating this finally

**Comment by TomasVotruba** [comment]
>  ...so no my commits were leaked into the repo :)

Oh no, that was not the reason. I made huge refactoring on adding types in methods and properties, voids, scalars, array etcs., so basically I had to recreate every interface from scratch. Copy-pasting PRs whould take months of rebase time and would not add much value.

I'm sorry if it was put in a wrong way :(

> Anyway, thanks for integrating this finally

:+1:

**Comment by TomasVotruba** [comment]
I've added your name to descrition so you don't feel left out, that's the least I could do.

**Comment by bocharsky-bw** [comment]
Ah, I see...

> 've added your name to descrition so you don't feel left out, that's the least I could do.

Thanks! :)

**Comment by lemoinem** [comment]
I've just had a bunch of my PRs closed referencing this one as well...
Really glad to see this finally going forward! (:

**Comment by TomasVotruba** [comment]
@lemoinem I've added you to PR description as well. Also I'm writing a post about DoctrineBehaviors 2.0 also with your credit for this feature here.

**Comment by lemoinem** [comment]
Thank you very much! It's great to see the project moving forward again.
Thank you for taking care of it and keep up the good work :)

**Comment by TomasVotruba** [comment]
> Thank you very much! It's great to see the project moving forward again.

It was about the god damned time ;) thanks for never stopping believing! :heart: 

<br>

I forgot to share it, there you go: https://www.tomasvotruba.cz/blog/2019/12/30/doctrine-behaviors-2-0-reloaded/#from-trait-to-interface

**Comment by lemoinem** [comment]
Great post!
It's very clear and helps a lot to understand what's going on and the value of the change!

**Pull request merged**
