### PR TITLE
TreeNodeMethodsTrait must be compatible with TreeNodeInterface

### PR DESCRIPTION
**Pull request by maxhelias**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Could you add failing test to show the bug you have before this changes? So we know we have it covered and it won't happen again

**Comment by maxhelias** [comment]
In fact, we don't have a php error but PhpStorm raise a warning
Capture d’écran 2020-10-27 à 13 41 48

**Comment by TomasVotruba** [comment]
It might be bug in PHPStorm resolution then.

The `self` in interface = the interface itself, so PHP code is correct here

**Comment by maxhelias** [comment]
Yes and no, as they are a php trait we would need more a way to link it with this interface. I did'nt find anything on the phpdoc level.

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.

**Pull request closed without merging**
