### PR TITLE
Function documented to receive null

### PR DESCRIPTION
**Pull request by crazycodr**
The documentation states that we should be able to set null to the deltedAt date which makes sense to allow "undeletion"

### CODE REVIEW

**Comment by crazycodr** [comment]
We need this at work for our project to continue, please consider merging ASAP.

**Comment by crazycodr** [comment]
My changes are passing but the the whole package has other errors. Can we still approve this and merge, thanks?

**Comment by akovalyov** [comment]
@crazycodr the phpdoc is invalid there, thank you for pointing this out. However, for "undeletion" functionaity you can use a method which is made [exactly for that](https://github.com/KnpLabs/DoctrineBehaviors/blob/977677d6645185b990607c136effefe08ce9b198/src/Model/SoftDeletable/SoftDeletableMethods.php#L32)

**Comment by akovalyov** [comment]
Closed by #220.

**Pull request closed without merging**
