### PR TITLE
Add "Uuidable" trait based on Ramsey UUID4

### PR DESCRIPTION
**Pull request by petegore**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Could you please take a look at Travis and fix your commits history?

**Comment by NiR-** [comment]
@petegore Good idea! There's been an architecture overhaul started times ago and still not finished at this time. It would merely get rid of the messy trait detection and instead use proper interfaces to detect when mapping is necessary. I think it would be cool if your PR could get this right from the beginning.

**Comment by TomasVotruba** [comment]
Pretty neat feature! I'll integrate it into next version, after the clean up

Thank you for the PR

**Comment by TomasVotruba** [comment]
Thank you for the feature! :+1: 

Rebased on current master in https://github.com/KnpLabs/DoctrineBehaviors/pull/450
and implemented

**Pull request closed without merging**
