### PR TITLE
Fixed support for PointType with Mysql.

### PR DESCRIPTION
**Pull request by kuczek**

### CODE REVIEW

**Comment by handosensei** [comment]
Nice work kuczek :+1: 
I am waiting your PR

**Comment by docteurklein** [comment]
let's merge it then :)

**Comment by docteurklein** [comment]
ha, it needs a rebase. Can you do that @kuczek ? Thanks :)

**Comment by kuczek** [comment]
@docteurklein You mean to squash commits?

**Comment by docteurklein** [comment]
no i meant rebase, like you did. Now I can merge (before, there were conflicts).
But you can squash if you wish :) Otherwise, let's merge this.

**Comment by kuczek** [comment]
@docteurklein No it cannot be one commit, but I'll squash them to 2, for 125 and for 145

**Comment by docteurklein** [comment]
ok thanks!

**Comment by kuczek** [comment]
@docteurklein Hi, sorry that it take so long. It should be ready to merge if tests will pass.

**Comment by docteurklein** [comment]
thanks :)

**Pull request merged**
