### PR TITLE
changelog: note breaking change about abstract translatable

### PR DESCRIPTION
**Pull request by Kocal**
See https://github.com/KnpLabs/DoctrineBehaviors/pull/448#issuecomment-578937662, thanks. :)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This could be handled better by instant upgrade with Rector.

What is the minimal diff that shows the change 1 to 2?

**Comment by Kocal** [comment]
Hum that's true, but I don't really think this can by handled properly by rector.

This is how we _fixed_ it, we keep the old `AbstractContentTranslation` class:

```diff
<?php

// ...

abstract class AbstractContent implements TranslatableInterface
{
    use TranslatableTrait;

+   public static function getTranslationEntityClass(): string
+   {
+       return self::class.'Translation';
+   }

    // ...
}
```

**Comment by TomasVotruba** [comment]
I see. Should be done.

 Could you add failing test case to repository here? I'll fix it and the prepare migration path

**Comment by Kocal** [comment]
I'm not sure of what I should really do here. :/
I've added some fixtures (abstract entity and its translation in _v1 way_) and a test, but I'm facing `General error: 1 no such table: AbstractV1TranslatableEntityTranslation` error :(

**Comment by TomasVotruba** [comment]
I'm not sure either, I only maintain this package for a few months and I'm not very active translation user.

**Comment by TomasVotruba** [comment]
Closing as stale

**Pull request closed without merging**
