### PR TITLE
Bugfix for Tree: getRealMaterializedPath

### PR DESCRIPTION
**Pull request by prof-web-coding**
See Added Test

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, thanks for fix + test. I don't use Tree at all, so I can't read the test.

Could you explain in human words what was the issue?

**Comment by prof-web-coding** [comment]
If I do ```setChildNodeOf(null);``` it should result in a materialized path of consisting of just the "MaterializedPathSeparator" (e.g. '/'). This was fine. If I then add a child to this node, the materialized path of of this child should be "MaterializedPathSeparator" plus the id of the parent node (e.g. '/1'). Without the fix, it was twice the "MaterializedPathSeparator" plus the id. (e.g. '//1');

**Comment by prof-web-coding** [comment]
Do you need more info @TomasVotruba ?

**Comment by TomasVotruba** [comment]
I see. All good, thanks

**Pull request merged**
