### PR TITLE
[Translatable] Rewrite Translatable/Translation to use Interfaces instead of Traits

### PR DESCRIPTION
**Pull request by lemoinem**
Here is the Translatable part for #241

### CODE REVIEW

**Comment by lemoinem** [comment]
I'm not entirely sure why the travis build failed, but it seems to have the same issue on master already, so... I'm gonna guess it's unrelated to this PR.

**Comment by Pierstoval** [comment]
```
s\Knp\DoctrineBehaviors\ORM\Timestampable
 [x] It should initialize create and update datetime when created
 [ ] It should modify update datetime when updated but not the creation datetime
 [ ] It should return the same datetime when not updated
 [ ] It should modify update datetime only once
```

Comes from timestampable ;)

**Comment by lemoinem** [comment]
@Pierstoval Oh, ok. I have the same fails in local... The errors are harder to spot with this output... (Which is new to me, too...) but now I know what to look for, it will easier. Thanks!

**Comment by docteurklein** [comment]
BTW, I think once we moved to interfaces, we can get rid of class analyzer. that would be so good

**Pull request closed without merging**
