### PR TITLE
Allow to install with phpstan-extensions installer

### PR DESCRIPTION
**Pull request by VincentLanglet**
Hi @TomasVotruba, according to https://github.com/phpstan/extension-installer#instructions-for-extension-developers
this would allow to use `phpstan/extension-installer` to automatically install this extension.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
The rector build seems unrelated ; dunno if I should fix it

**Comment by TomasVotruba** [comment]
Hi, you can apply Rector by running it: 

```bash
vendor/bin/rector process
```

I'll review changes after the CI passed :+1:

**Comment by VincentLanglet** [comment]
> Hi, you can apply Rector by running it:
> 
> ```shell
> vendor/bin/rector process
> ```
> 
> I'll review changes after the CI passed 👍

Done

**Comment by TomasVotruba** [comment]
Awesome, thank you :+1:

**Comment by VincentLanglet** [comment]
> Awesome, thank you 👍

You're welcome. If you have time for a release it would be great.

**Comment by TomasVotruba** [comment]
There you go https://github.com/KnpLabs/DoctrineBehaviors/releases/tag/2.6.2 :slightly_smiling_face:

**Comment by VincentLanglet** [comment]
Thanks a lot. Just tried and it works perfectly

**Pull request merged**
