### PR TITLE
isempty(): Fix code according to PSR or symfony codestyles

### PR DESCRIPTION
**Pull request by corentinheadoo**

### CODE REVIEW

**Comment by Pierstoval** [comment]
Shouldn't you rename this PR?

**Comment by corentinheadoo** [comment]
I created a new branch than https://github.com/KnpLabs/DoctrineBehaviors/pull/332 due to a conflict.

**Comment by Pierstoval** [comment]
You could just rebase your branch and fix conflicts manually instead of creating another branch

**Comment by corentinheadoo** [comment]
Ok, I fixed problems in https://github.com/KnpLabs/DoctrineBehaviors/pull/332.

**Pull request closed without merging**
