### PR TITLE
[Translatable] allow to add translatable behavior to abstract class and works with inheritance

### PR DESCRIPTION
**Pull request by almacbe**
There were some errors when you have some classes like the test that I have created and with the changes that I propuse I fix them.

What do you think?

### CODE REVIEW

**Comment by almacbe** [comment]
Could someone help me with the error in the tests? Some advise, please

**Comment by almacbe** [comment]
Some feedback?

**Comment by Einenlum** [comment]
Thanks for your work @almacbe and sorry for the long delay.
Looks good to me. @docteurklein is it ok for you?

**Comment by almacbe** [comment]
Your welcome. I hope we can merge as soon as possible if everything is ok.

**Comment by almacbe** [comment]
Are there something that I can do to about this @Einenlum @docteurklein or do I have to wait?

**Comment by almacbe** [comment]
I have updated the PR and I think now it is ready for merging. Could you have a look @Einenlum @docteurklein @knpEdgar ?

We have fixed test compatibility error with dev-master of doctrine/common by disallowing to mock `setSchemaAssetsFilter` and `getSchemaAssetsFilter` of Doctrin\ORM\Configuration. 

BTW, we use this lib in our core and we could help to maintain it. So we are pleased to help.

**Comment by Einenlum** [comment]
Hi @almacbe,
I'm not working at KNPLabs anymore (@docteurklein either), so we don't have the rights on this repository anymore.
Maybe @pedrotroller, NiR- or @AntoineLelaisant could help you on this!

**Comment by TomasVotruba** [comment]
Thank you for your work, merged :+1:

**Comment by almacbe** [comment]
Finally, thanks so much, after three years :-D, but I think you steal my contribution :-P

**Comment by fodaveg** [comment]
well done ~@TomasVotruba~ i mean... @almacbe !!

**Comment by TomasVotruba** [comment]
@almacbe Not an intention. I made huge refactoring on adding types in methods and properties, voids, scalars, array etcs., so basically I had to recreate every interface from scratch. Copy-pasting PRs whould take months of rebase time and would not add much value.

**Comment by golossus** [comment]
Rebasing time longer than 3 years? I don't think so.

**Comment by sangarbe** [comment]
Rebasing time longer than three years waiting? I don't think so @TomasVotruba

**Comment by TomasVotruba** [comment]
Nono, longer than intergrating it manually with current `master`.

**Comment by almacbe** [comment]
I understand it @TomasVotruba No worry, but there are other ways to keep the contributions as add co-authors. But forget it, it is fine. Thanks anyway, I'm happy that someone could update the repo finally if you need help I know a few people that use a lot this repo and they could be interested in contribute.

**Pull request closed without merging**
