### PR TITLE
Sluggable. Use default locale when generating entity slug

### PR DESCRIPTION
**Pull request by epashkov**
Hi there!

Relates issue: https://github.com/KnpLabs/DoctrineBehaviors/issues/559

I have a little difficulty with these PR. I do not know how to run the tests correctly and so I can not fix them.

Could somebody please help me?

### CODE REVIEW

**Comment by epashkov** [comment]
Also we need slug entity field to be nullable. I use Sonata admin and there is related issue https://github.com/sonata-project/SonataAdminBundle/issues/5732

> Sonata uses Symfony forms bound to entities directly, even for the create form, that means that every field in your entity has to > have a nullable getter, or a default value that is not null.

**Comment by epashkov** [comment]
How to restart deployment checks?

I fix tests, but I see that The operation was canceled.

**Comment by TomasVotruba** [comment]
Hi, just push another commit. I've triggered it manually, but most jobs are failing

**Comment by epashkov** [comment]
@TomasVotruba thanks. All tests are passed now, but static analysis is not. And I still don't understand what is wrong.

**Comment by epashkov** [comment]
It seems that CI not working properly. I can run all checks on my local machine and no errors there.

**Pull request closed without merging**
