### PR TITLE
Fix #267: if no config specified all behaviors are enabled

### LINKED ISSUE #267: Commit a52a92a disables all subscribers
According to the updated documentation, commit a52a92a intended to make all configurations enabled by default when the root node `knp_doctrine_behaviors` is empty. However, when tested on Symfony 2.7.6, the actual behavior is that all behaviors are disabled by default. Looks like the `treatNullLike([... => true ])` in `Configuration` class has no effect. Can anyone verify this behavior? Thanks.

### PR DESCRIPTION
**Pull request by NiR-**

### CODE REVIEW

**Comment by docteurklein** [comment]
fixes #297, #292, #286, #281, #272, #270

**Comment by yvesblancquaert** [comment]
Error after update to 1.3.1
capture

**Comment by yvesblancquaert** [comment]
v1.3.2 didn't solve issue #297 
capture1

**Comment by docteurklein** [comment]
@yvesblancquaert thanks for the quick feedback!
I guess we need to figure out what's the problem first, before tagging anything :)

Could you check if the TranslatableSubscriber class is even correctly called?
It seems that it does not automagically map the IDs anymore (https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/ORM/Translatable/TranslatableSubscriber.php#L93).

Can you debug this part and look if `mapId` is called?

**Pull request merged**
