### PR TITLE
Add doctrine join table inheritance compatibility

### PR DESCRIPTION
**Pull request by MichaelBrauner**
This PR adds a failing test and a fix for #307 #317 and #336.

**As a short summary:** 

Whenever you use doctrine joined inheritance you get a `Doctrine\DBAL\Schema\SchemaException: There is no column with name 'translatable_id' on table`. 

This is because a unique constraint is going to be set for the translation subclass but this class don't have this column. This comment describes it well and also suggest the fix: https://github.com/KnpLabs/DoctrineBehaviors/issues/307#issuecomment-231264716

### CODE REVIEW

**Comment by MichaelBrauner** [comment]
I will work on the failing checks.

**Comment by TomasVotruba** [comment]
Hi, thanks for the PR :+1:  The coding standard can be fixed with:

```bash
composer fix-cs
```

See https://github.com/KnpLabs/DoctrineBehaviors#3-steps-to-contribute

**Comment by MichaelBrauner** [comment]
A few PHPStan issues remain.

```shell
 ------------------------------------------------------------------------
  tests/Fixtures/Entity/Translatable/ExtendedTranslatableEntityWithJoinTableInheritanceTranslation.php:9
 ------------------------------------------------------------------------
  - '#There should be no empty class#'
  ```

This is a common usecase. Imagine you have a `Page` entity with a translated `title`. Than u want to have a `ContactPage` extended from `Page`. The translation has to extend PageTranslation but as long as you don't want to translate any `ContactPage`fields this class needs to be empty.

```shell
------------------------------------------------------------------------
  tests/Fixtures/Entity/Translatable/TranslatableEntityWithJoinTableInheritance.php:16
 ------------------------------------------------------------------------
  - '#Attribute must have all names explicitly defined#'
 ------------------------------------------------------------------------

 ------------------------------------------------------------------------
  tests/Fixtures/Entity/Translatable/TranslatableEntityWithJoinTableInheritanceTranslation.php:17
 ------------------------------------------------------------------------
  - '#Attribute must have all names explicitly defined#'
 ------------------------------------------------------------------------
```

This is the recommended implemenation. And the `#[Entity]` annotation is used this way inside the whole project.

Can I update the `phpstan.neon` file to ignore these messages?

**Comment by TomasVotruba** [comment]
The ` - '#There should be no empty class#'` can be ignored.

The rest should be fixed to make argument name explicit.

**Comment by TomasVotruba** [comment]
> And ... I don't undestand why the last Rector run failed. I did not change anything related to this.

Skip that for now, as it's probably related with new release. I'll check if after merge.

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Comment by MichaelBrauner** [comment]
> Thank you 👏

Thank you for allowing me to do that. And for reacting so quickly.

I also will write some documentation related to this PR in the next few days.

**Comment by TomasVotruba** [comment]
> I also will write some documentation related to this PR in the next few days.

That would be very useful improvement here. Thanks a lot for your work :+1:

**Pull request merged**
