### PR TITLE
Default locale provider handling

### PR DESCRIPTION
**Pull request by danut007ro**
Hello,

This pull request aims to use the `kernel.default_locale` parameter if no parameter named `locale` is set.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, what happens if no `kernel.default_locale` is used?

**Comment by danut007ro** [comment]
Hello,

It should return `null` since it will catch the exception. This should happen also if no `locale` parameter was set. On my sf5 the other exception was thrown, which I added to `catch` clause.

**Comment by TomasVotruba** [comment]
All right, let's give it a go.

Thank you

**Comment by smatyas** [comment]
This fixes a bug in a symfony console command case for us.

Using the current (2.0.3) version, the following exception is thrown:

```
In srcApp_KernelProdContainer.php line 10922:
                                                                              
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The parameter "locale" must be defined.                                     
                                                                              

Exception trace:
  at /srv/life-portal/var/cache/prod/Container04Ogf3c/srcApp_KernelProdContainer.php:10922
 Container04Ogf3c\srcApp_KernelProdContainer->getParameter() at /srv/life-portal/vendor/symfony/dependency-injection/ParameterBag/ContainerBag.php:41
 Symfony\Component\DependencyInjection\ParameterBag\ContainerBag->get() at /srv/life-portal/vendor/knplabs/doctrine-behaviors/src/Provider/LocaleProvider.php:68
 Knp\DoctrineBehaviors\Provider\LocaleProvider->provideFallbackLocale() at /srv/life-portal/vendor/knplabs/doctrine-behaviors/src/EventSubscriber/TranslatableSubscriber.php:177
 Knp\DoctrineBehaviors\EventSubscriber\TranslatableSubscriber->setLocales() at /srv/life-portal/vendor/knplabs/doctrine-behaviors/src/EventSubscriber/TranslatableSubscriber.php:74
 Knp\DoctrineBehaviors\EventSubscriber\TranslatableSubscriber->postLoad() at /srv/life-portal/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:58
 Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent() at /srv/life-portal/vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php:117
 Doctrine\ORM\Event\ListenersInvoker->invoke() at /srv/life-portal/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/HydrationCompleteHandler.php:95
 Doctrine\ORM\Internal\HydrationCompleteHandler->hydrationComplete() at /srv/life-portal/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:3581
 Doctrine\ORM\UnitOfWork->hydrationComplete() at /srv/life-portal/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php:151
 Doctrine\ORM\Internal\Hydration\ObjectHydrator->cleanup() at /srv/life-portal/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php:155
 Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll() at /srv/life-portal/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1001
 Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache() at /srv/life-portal/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:947
 Doctrine\ORM\AbstractQuery->execute() at /srv/life-portal/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:750
...
```

What's the plan on tag a new release @TomasVotruba ? :)

Anyway, thanks for this fix!

**Comment by TomasVotruba** [comment]
There you go https://github.com/KnpLabs/DoctrineBehaviors/releases/tag/v2.0.4 :)

**Pull request merged**
