### PR TITLE
Fix broken old bandle register class

### LINKED ISSUE #542: Release 2.0.2 BC breaks due to bundle namespace change
Bundle namespace changed from   
`Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle` to   `Knp\DoctrineBehaviors\DoctrineBehaviorsBundle`  
So we need to update our `config/bundles.php`

Change comes from this PR https://github.com/KnpLabs/DoctrineBehaviors/pull/534 
Maybe reverting it and release a 2.0.3? 

I guess a lot of people will update their vendors soon, due to todays symfony security release 4.4.7 / 5.0.7.

### PR DESCRIPTION
**Pull request by uginroot**
closes #542

### CODE REVIEW

**Comment by uginroot** [comment]
ecs does not allow class names to be called by the same name, even in different namespaces, but in this case it must be done. What to do in this case?

**Comment by uginroot** [comment]
I apologize for spam, the local version of ecs on windows works a little wrong

**Comment by TomasVotruba** [comment]
No troubles. Could you squash it into 1 commit? I'll handle the cs

**Comment by bobdenotter** [comment]
Thank you for looking into this, @uginroot and @TomasVotruba 🙏

**Comment by TomasVotruba** [comment]
Thanks

**Comment by TomasVotruba** [comment]
Just released v2.0.3 with this fix.
Thanks for the help!

**Pull request merged**
