### PR TITLE
Allow someone to extends a Traits

### PR DESCRIPTION
**Pull request by skrosoft**
Allow someone to extends a Traits.

Exemple:

```
<?php
// ...

use Knp\DoctrineBehaviors\Model\Tree\Node;

trait MySomethingable
{
    use Node;

    // ...
	
    public function myFunction(MyInterface $parent = null)
    {
        // ...

        $this->setParentNode($parent);

        // ...
    }
	
    // ...
}
```

:)

### CODE REVIEW

**Comment by Einenlum** [comment]
Hi @skrosoft.

If you want to "extend" traits, you can always create a trait that uses another trait, like this answer: https://stackoverflow.com/a/37687295

**Comment by skrosoft** [comment]
Hi @Einenlum . Yes I know how to “extend” traits. But without my code, if you extend a trait, the command “doctrine:scheme:update” will not create the new fields in the database. Please check my code and tell me if you need more information.

**Comment by skrosoft** [comment]
Ps: in the case of “Tree/Node”, the field “materialized path” would not be created.

**Comment by TomasVotruba** [comment]
Could you add test for it?

**Comment by TomasVotruba** [comment]
This will be replaced by interfaces, see #241

**Pull request closed without merging**
