### PR TITLE
Fix Timestampable tests

### PR DESCRIPTION
**Pull request by lemoinem**
Here is a PR to fix the tests in `master` as suggested in #326 ;) Hope that helps.

### CODE REVIEW

**Comment by lemoinem** [comment]
@bocharsky-bw @docteurklein Take a look at the travis check ;)

**Comment by docteurklein** [comment]
yay! thanks so much !

**Comment by bocharsky-bw** [comment]
All tests are passed 🎉 

Thank you @lemoinem !

**Comment by lemoinem** [comment]
You're welcome ;) Happy to help!

**Pull request merged**
