### PR TITLE
Test against three last doctrine common versions

### PR DESCRIPTION
**Pull request by akovalyov**

### CODE REVIEW

**Comment by docteurklein** [comment]
2.6 is 5.5+. what do we do?

**Comment by akovalyov** [comment]
@docteurklein you mean with the build or with 5.4 support drop?

**Comment by docteurklein** [comment]
@akovalyov I meant with 5.4.

**Comment by akovalyov** [comment]
@docteurklein PHP 5.3 has reached its EOL 3 months ago. So, I suggest to tag the last minor release for 5.4 and to add 5.5 as a minimum.

**Comment by docteurklein** [comment]
Totally. we'll just tag a last release for the lost people still using 5.3/5.4 (like me :))
next release is a minor change with php version drop!

**Comment by akovalyov** [comment]
@docteurklein so, is it time now for this PR?

**Pull request merged**
