### PR TITLE
fix: compatibility with TreeNodeInterface

### PR DESCRIPTION
**Pull request by netbull**

### CODE REVIEW

**Comment by netbull** [comment]
Anyone? Is this project dead?

**Comment by Kocal** [comment]
Hi, the project is not dead, @TomasVotruba is just busy with something else.

But I think you can start to make the CI green! :)

**Comment by Kocal** [comment]
That's how free and open-source work, Tomas does not owe anything to us. 

If it's urgent for you, you can use your own fork instead.

**Comment by netbull** [comment]
@Kocal I don't get it really.. There was an issue with this bundle, I submitted a fix. So I spent my time to do the fix and 19 days so far the code is not merged..

Don't get me wrong I don't need this anyway and I'm not on a rush. Just explain to someone else how the open-source works.

**Comment by TomasVotruba** [comment]
@netbull Thank you for pull-request :+1: I've probably missed this in amount of open-source notifications I'm getting. I'm sorry about that.

I've just updated to PHPStan Symplify rule sets, that include a rule that checks exactly this types conflitcs with traits/classes/interfaces: https://github.com/symplify/phpstan-rules/blob/main/docs/rules_overview.md#checkparentchildmethodparametertypecompatiblerule

Saying that, I've fixed this ~30 minutes ago and released in 2.3.0: https://github.com/KnpLabs/DoctrineBehaviors/commit/35ba29cefdfa18778f5273e1dc7c156f43d92340#diff-b02f17f75334fed0fdfe5a8777457e2e429c746224a9f7c2b661b3588eeb9819




@Kocal Thank you for support here :heart:

**Comment by netbull** [comment]
@TomasVotruba don't worry :) Thank you!

**Pull request closed without merging**
